config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  get :follows, on: :member
  get :followers, on: :member
  end
  
  get '/search', to: 'searches#search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end 

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, destroy:false
  
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :public_action]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
    else
  end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.find(params[:id])
    @book_comment.destroy
  end

  private
  def book_comment_params
   params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path, alert: 'Warring!!'
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    redirect_to(books_url) unless @book.user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :book_params

  def create
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.new(book_id: book.id)
   favorite.save
  end

  def destroy
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.find_by(book_id: book.id)
   favorite.destroy
  end

  private
 #books/show画面で定義した＠bookを反映させるための記述
  def book_params
    @book = Book.find(params[:book_id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'foward'
        User.where('name LIKE ?', '%'+content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content+'%')
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'foward'
        Book.where('title LIKE ?', '%'+content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content+'%')
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :following, :follwers]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @user =current_user
    @users = User.all
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
    if
      @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def correct_user
   @user = User.find(params[:id])
   if current_user != @user
    redirect_to user_path(current_user)
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$(".commentsArea").html("<%= j(render 'books/comment', { book: @book, book_comment: @book_comment }) %>");
$(".inputComment").val('');

app/views/book_comments/destroy.js.erb
$(".commentsArea").html("<%= j(render 'books/comment', { book: @book, book_comment: @book_comment }) %>");
$(".inputComment").val('');

app/views/books/_comment.html.erb
<table class="table">
    <tbody>
      <% book.book_comments.each do |book_comment| %>
        <% book_comment_user = book_comment.user %>
        <tr>
          <td>
            <%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
              <%= attachment_image_tag book_comment_user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no-image-icon.jpg" %><br/>
              <%= book_comment_user.name %>
            <% end %>
            <td><%= book_comment.comment %></td>
          </td>
          <% if book_comment.user.id == current_user.id %>
            <td><%= link_to "Destroy", book_book_comment_path(book_comment.book.id, book_comment.id), method: :delete, remote: true, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= form_with model:[book, book_comment] do |f| %>
     <%= f.text_area :comment, size:"90x5", class: "inputComment" %><br>
     <%= f.submit "送信" %>
    <% end %>
  </div>

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn"><%= render 'favorites/favorite', book: book %></td>
        <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search_index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <% if books.exists? %>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody id="book">
          <% books.each do |book| %>
          <tr>
            <td>
              <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no-image-icon.jpg" %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <% if book.user == current_user %>
              <td><%= link_to "編集", edit_book_path(book) %></td>
              <td><%= link_to "削除", book_path(book), method: :delete, remote: true %></td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
     <p>一致する検索結果はありません</p>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label><br/>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label><br/>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %>

<div id="error_explanation"></div>
    <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
</div>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 20, 20, fallback: "no-image-icon.jpg"),user_path(book.user) %><br/>
            </td>
            <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
            <td><%= book.body %></td>
            <td id="favorite_btn_<%= book.id %>">
              <%= render 'favorites/favorite', book: book %>
            </td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %><!--新規投稿成功時のflash-->
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 20, 20, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="favorite_btn_<%= @book.id %>">
            <%= render 'favorites/favorite', book: @book %>
          </td>
          <td>コメント数:<%= @book.book_comments.count %></td>
          <% if @user.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <div class="commentsArea">
        <%= render 'books/comment', book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
    <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_btn_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searches/_searches_form.html.erb
<% if user_signed_in? %>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag 'content' %>
    <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
    <%= submit_tag '検索' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/search_user_index', users: @records %>
<% else @model == 'book' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/search_index', books: @records %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% unless current_user == user %>
            <% if user.followed_by?(current_user) %>
              <th><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-info" %></th>
            <% else %>
              <th><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %></th>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag(user, :profile_image, :fill, 60, 60, fallback: "no-image-icon.jpg") %>
<table class='table'>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, follows_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
  <td>
    <% unless current_user == user %>
      <% if user.followed_by?(current_user) %>
       <th><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-info" %></th>
      <% else %>
       <th><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %></th>
      <% end %>
    <% end %>
  </td>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/_search_user_index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <% if users.exists? %>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th colspan="6"></th>
        </tr>
      </thead>
      <tbody id="user">
      <% users.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no-image-icon.jpg" %>
          </td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td>
            <% unless current_user == user %>
              <% if user.followed_by?(current_user) %>
                <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-success" %>
              <% else %>
                <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-info" %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to 'Show', user_path(user.id) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <% else %>
      <p>一致する検索結果はありません</p>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<div class="container px-5 px-sm-0">
  <div class="row">
    <table class="table">
      <% if @users.exists? %>
        <thead>
          <tr>
           <th>image</th>
           <th>name</th>
           <th></th>
           <th></th>
           <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
             <%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no-image-icon.jpg" %>
            </td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
        <% end %>
        </tbody>
    </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
  </div>
</div>

app/views/users/follows.html.erb
<h2>Follows Users</h2>
<div class="container px-5 px-sm-0">
  <div class="row">
    <table class="table">
      <% if @users.exists? %>
        <thead>
          <tr>
           <th>image</th>
           <th>name</th>
           <th></th>
           <th></th>
           <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
             <%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no-image-icon.jpg" %>
            </td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
        <% end %>
        </tbody>
    </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
     <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'users/index',users: @users %>
     </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>